[tool.poetry]
name = "fhir-pyrate"
version = "0.2.1"
description = "FHIR-PYrate is a package that provides a high-level API to query FHIR Servers for bundles of resources and return the structured information as pandas DataFrames. It can also be used to filter resources using RegEx and SpaCy and download DICOM studies and series."
license = "MIT"
authors = ["Rene Hosch <rene.hosch@uk-essen.de>", "Giulia Baldini <giulia.baldini@uk-essen.de>"]
readme = "README.md"
repository = "https://github.com/UMEssen/FHIR-PYrate"
keywords = ["python", "fhir", "data-science", "fhirpath", "healthcare"]
include = ["LICENCE"]
packages = [
    { include = "fhir_pyrate" },
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
# Optional dependencies
SimpleITK = { version = "^2.3.1", optional = true }
pydicom = { version = "^2.4.4", optional = true }
dicomweb-client = { version = "^0.59.1", optional = true }
spacy = { version = "^3.7.2", optional = true }
# Core dependencies
numpy = "^1.24.0"
pandas = "^2.2.0"
tqdm = "^4.66.1"
requests = "^2.31.0"
PyJWT = "^2.8.0"
fhirpathpy = "^0.2.2"
requests-cache = "^1.1.1"

[tool.poetry.extras]
downloader = ["SimpleITK", "pydicom", "dicomweb-client"]
miner = ["spacy"]
all = ["SimpleITK", "pydicom", "dicomweb-client", "spacy"]

[tool.poetry.dev-dependencies]
python-dotenv = "^1.0.0"
pre-commit = "^3.6.0"
flake8 = "^7.0.0"
mypy = "^1.8.0"
black = "^24.1.1"
beautifulsoup4 = "^4.12.2"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = true
in-project = true

[tool.isort]
profile = "black"
line_length = 88